name: Relase Build Test (Simulator + Shell)


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-driver:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages for SSDSimulator
      run: nuget restore SSDSimulator/SSDSimulator.sln

    - name: Build SSDSimulator (Release)
      run: msbuild SSDSimulator/SSDSimulator.sln /p:Configuration=Release

    - name: Upload ssd.exe
      uses: actions/upload-artifact@v4
      with:
        name: ssd_exe
        path: SSDSimulator/x64/Release/ssd.exe

  build-shell:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages for TestShell
      run: nuget restore TestShell/TestShell.sln

    - name: Build TestShell (Release)
      run: msbuild TestShell/TestShell.sln /p:Configuration=Release

    - name: Upload TestShel.exe
      uses: actions/upload-artifact@v4
      with:
        name: TestShell_exe
        path: TestShell/x64/Release/TestShell.exe